// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieBookingSystem.Data;

#nullable disable

namespace MovieBookingSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251026155505_AddSeatCategoryToBooking")]
    partial class AddSeatCategoryToBooking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MovieBookingSystem.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfTickets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Seats")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShowtimeId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MovieBookingSystem.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The epic conclusion to the Infinity Saga.",
                            Duration = new TimeSpan(0, 3, 1, 0, 0),
                            Genre = "Action",
                            ImageUrl = "/images/avengers.jpg",
                            IsActive = true,
                            Language = "English",
                            ReleaseDate = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 280m,
                            Title = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spider-Man identity revealed with multiverse.",
                            Duration = new TimeSpan(0, 2, 28, 0, 0),
                            Genre = "Action",
                            ImageUrl = "/images/spiderman.jpg",
                            IsActive = true,
                            Language = "English",
                            ReleaseDate = new DateTime(2021, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 250m,
                            Title = "Spider-Man: No Way Home"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dark knight investigation in Gotham city.",
                            Duration = new TimeSpan(0, 2, 56, 0, 0),
                            Genre = "Action",
                            ImageUrl = "/images/batman.jpg",
                            IsActive = true,
                            Language = "English",
                            ReleaseDate = new DateTime(2022, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 220m,
                            Title = "The Batman"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A fictional story about two Indian revolutionaries.",
                            Duration = new TimeSpan(0, 3, 7, 0, 0),
                            Genre = "Action/Drama",
                            ImageUrl = "/images/rrr.jpg",
                            IsActive = true,
                            Language = "Hindi/Telugu",
                            ReleaseDate = new DateTime(2022, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 200m,
                            Title = "RRR"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rocky continues his rise to power in the gold mining world.",
                            Duration = new TimeSpan(0, 2, 48, 0, 0),
                            Genre = "Action",
                            ImageUrl = "/images/kgf2.jpg",
                            IsActive = true,
                            Language = "Hindi/Kannada",
                            ReleaseDate = new DateTime(2022, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 180m,
                            Title = "KGF Chapter 2"
                        });
                });

            modelBuilder.Entity("MovieBookingSystem.Models.Showtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ShowDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Theater")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Showtimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 150,
                            IsActive = true,
                            MovieId = 1,
                            ShowDateTime = new DateTime(2025, 10, 28, 15, 55, 4, 627, DateTimeKind.Local).AddTicks(3334),
                            Theater = "PVR Cinemas - Forum Mall",
                            TotalSeats = 150
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 120,
                            IsActive = true,
                            MovieId = 2,
                            ShowDateTime = new DateTime(2025, 10, 26, 23, 25, 4, 627, DateTimeKind.Local).AddTicks(3349),
                            Theater = "INOX - Magnolia Mall",
                            TotalSeats = 120
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 100,
                            IsActive = true,
                            MovieId = 3,
                            ShowDateTime = new DateTime(2025, 10, 29, 17, 25, 4, 627, DateTimeKind.Local).AddTicks(3352),
                            Theater = "Cinepolis - Urban Center",
                            TotalSeats = 100
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 200,
                            IsActive = true,
                            MovieId = 4,
                            ShowDateTime = new DateTime(2025, 10, 28, 12, 25, 4, 627, DateTimeKind.Local).AddTicks(3354),
                            Theater = "PVR Cinemas - Phoenix Mall",
                            TotalSeats = 200
                        },
                        new
                        {
                            Id = 5,
                            AvailableSeats = 180,
                            IsActive = true,
                            MovieId = 5,
                            ShowDateTime = new DateTime(2025, 10, 30, 18, 25, 4, 627, DateTimeKind.Local).AddTicks(3356),
                            Theater = "INOX - Nexus Mall",
                            TotalSeats = 180
                        });
                });

            modelBuilder.Entity("MovieBookingSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@moviebook.com",
                            IsAdmin = true,
                            Name = "Admin User",
                            Password = "admin123",
                            Phone = "1234567890"
                        });
                });

            modelBuilder.Entity("MovieBookingSystem.Models.Booking", b =>
                {
                    b.HasOne("MovieBookingSystem.Models.Showtime", "Showtime")
                        .WithMany("Bookings")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieBookingSystem.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Showtime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieBookingSystem.Models.Showtime", b =>
                {
                    b.HasOne("MovieBookingSystem.Models.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieBookingSystem.Models.Movie", b =>
                {
                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("MovieBookingSystem.Models.Showtime", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("MovieBookingSystem.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
